---
title: "LeafletMap"
author: "Gaayathri Iyer"
date: "1/1/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
### This is a simple project using Leaflet to draw a map

##### Include the required library

```{r}
library(dplyr)
library(ggplot2)
library(rjson)
library(jsonlite)
library(leaflet)
library(RCurl)
library(httr)
```

##### Let us take this one step further and read 

```{r}
# you can then pipe this
water_data_df <- fromJSON("WaterQuality.json") %>%
      flatten(recursive = TRUE) # remove the nested data frame

# turn columns to numeric and remove NA values
water_data_df <- water_data_df %>%
      mutate_at(vars(amount, location.latitude, location.longitude), funs(as.numeric)) %>%
      filter(!is.na(location.latitude))
```
```{r}
print(water_data_df)
# create leaflet map
water_locations_map <- leaflet(water_data_df) %>%
      addTiles() %>%
      addMarkers(lng = ~location.longitude,
                 lat = ~location.latitude,
                 popup = ~station_name)

 water_locations_map
 ```
